name: Run scrapping script to get ICNF data

on:
  schedule:
    # Configs when to run this script, helpful website: https://crontab.guru/
    - cron: "30 14 * * *"
    

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run script
        run:  python xmlretriever.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: ICNF Updated
          branch: ${{ github.head_ref }}

