# This is a basic workflow to help you get started with Actions

name: ICNF DATA SCRAPPER DAILY

# Controls when the workflow will run / Helpful website: https://crontab.guru/
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Runs a single command using the runners shell
      - name: Run Scripts
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run App 
        run: updater.py
      # Commit New Data 
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: ICNF DATA SCRAPPING SUCCESSFUL 
          branch: ${{ github.head_ref }}
